spring.application.name=desafio-anota-ai
aws.acceskeyId=${AWS_ACCESS_KEY_ID}
aws.secretkey=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2
aws.sns.topic.catalog.arn=arn:aws:sns:us-east-2:959455446565:catalog-emit